version: '3.8'

services:
  cpp:
    container_name: cpp
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IWYU_TAG: "0.21"
    volumes:
      - ../:/workspace
    working_dir: /workspace
    command: sleep infinity
    tty: true
    stdin_open: true
    user: "1000:1000"
    environment:
      - DEVCONTAINER_ENV=1